version: '3.8'

services:
  ipfix-collector:
    build: .
    ports:
      - "4739:4739/udp"
      - "2112:2112"
    restart: unless-stopped
    environment:
      - GOMAXPROCS=4

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - ipfix-collector

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
